config/routes.rb
Rails.application.routes.draw do

  root 'cars#index'

  resources :cars


end

app/models/car.rb
class Car < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :find_car, only: [:edit, :update]

  def index
    @cars = Car.all
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.save
    redirect_to cars_path,
      notice: "#{@car.year} #{@car.make} #{@car.model} created"
  end

  def show
    @car = Car.find(params[:id])
  end

  def edit
  end

  def update
      @car.update(car_params)
        redirect_to cars_path,
      notice: 'Car was successfully updated.'
  end

  private

  def car_params
    params.required(:car).permit(:year, :make, :model, :price)
  end

  def find_car
    @car = Car.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |form| %>

  <div class="field">
    <%= form.label :make %><br>
    <%= form.text_field :make %>
  </div>
  <div class="field">
    <%= form.label :model %><br>
    <%= form.text_field :model %>
  </div>
  <div class="field">
    <%= form.label :year %><br>
    <%= form.text_field :year %>
  </div>
  <div class="field">
    <%= form.label :price %><br>
    <%= form.text_field :price %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h2>Editing car</h2>

<%= render 'form' %>

app/views/cars/index.html.erb
<h1>Listing cars</h1>

<table>
  <thead>
  <tr>
    <th>make</th>
    <th>model</th>
    <th>year</th>
    <th>price</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @cars.each do |car| %>
    <tr>
      <td><%= car.make %></td>
      <td><%= car.model %></td>
      <td><%= car.year %></td>
      <td><%= car.price %></td>
      <td><%= link_to 'Show', car %></td>
      <td><%= link_to 'Edit', edit_car_path(car) %></td>
      <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h2> New Car</h2>

<%= form_for(@car) do |form| %>
  <p>
    <%= form.label :make %>
    <%= form.text_field :make %>
  </p>
  <p>
    <%= form.label :model %>
    <%= form.text_field :model; %>
   </p>
  <p>
    <%= form.label :year %>
    <%= form.text_field :year %>
   </p>
  <p>
    <%= form.label :price %>
    <%= form.text_field :price %>
   </p>

  <%= form.submit %>

<% end %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Make:</strong>
  <%= @car.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Year:</strong>
  <%= @car.year %>
</p>

<p>
  <strong>Price:</strong>
  <%= @car.price %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DavinciMotors</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
  <div class='flash' id='<%= key %>'>
    <%= value %>
  </div>
<% end %>

<%= yield %>

</body>
</html>